name: GitHub Action next2 flow to Docker hub 

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Budowa i publikacja obrazw na repozytorium
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: QEMU set-up
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dockerfile.v1
          push: true
          tags: |
            svikt02/lab7:action1
          platforms: linux/amd64,linux/arm64,linux/arm/v7
